# Generated by Django 3.2.5 on 2022-09-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightage',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='weightage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.RemoveField(
            model_name='story',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Weightage',
        ),
    ]
