# Generated by Django 3.2.5 on 2022-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20220920_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='upload',
        ),
        migrations.AddField(
            model_name='storystatus',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/story-images'),
        ),
    ]
