# Generated by Django 3.2.5 on 2022-09-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20220920_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='media/story-images')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.story')),
            ],
        ),
    ]
