# Generated by Django 3.2.5 on 2022-09-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storystatus',
            name='upload',
        ),
    ]
