# Generated by Django 3.2.5 on 2022-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_remove_storystatus_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
